version: '3.8'

services:
  # .NET development container
  api:
    build:
      context: ./
      dockerfile: RecipeProcessing.Api/Dockerfile
      target: dev
      args:
        BUILD_CONFIGURATION: Debug  # Use Debug mode for development
    volumes:
      - ./RecipeProcessing.Api:/src
      - ~/.nuget/packages:/root/.nuget/packages
      - ./Config/OpenAi/Prompts:/Config/OpenAi/Prompts
    ports:
      - "5047:5047"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5047 
      - OpenAi:ApiKey=${OpenAi_ApiKey}
    command: ["dotnet", "watch", "run", "--project", "/src/RecipeProcessing.csproj"]