version: '3.8'

services:

  # .NET development container
  api:
    build:
      context: ./
      dockerfile: RecipeProcessing.Api/Dockerfile
      target: dev
      args:
        BUILD_CONFIGURATION: Debug # Use Debug mode for development
    volumes:
      - ./RecipeProcessing.Api:/src
      - ~/.nuget/packages:/root/.nuget/packages
      - ./Config/OpenAi/Prompts:/Config/OpenAi/Prompts
    ports:
      - "5047:5047"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5047
      - OpenAi:ApiKey=${OpenAi_ApiKey}
    depends_on:
      - db
    command: [ "dotnet", "watch", "run", "--project", "/src/RecipeProcessing.csproj" ]

  # Postgres database
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mealio_db_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
