version: '3.8'

services:

  # .NET development container
  api:
    build:
      context: ./
      dockerfile: RecipeProcessing.Api/Dockerfile
      target: dev
      args:
        BUILD_CONFIGURATION: Debug # Use Debug mode for development
    volumes:
      - ./RecipeProcessing.Api:/src
      - ~/.nuget/packages:/root/.nuget/packages
      - ./Config/OpenAi/Prompts:/Config/OpenAi/Prompts
    ports:
      - "5047:5047"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5047
      - OpenAi:ApiKey=${OpenAi_ApiKey}
    depends_on:
      - db
    command: [ "dotnet", "watch", "run", "--project", "/src/RecipeProcessing.csproj" ]

  # Postgres database
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mealio_db_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_management:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@localhost.com
      PGADMIN_DEFAULT_PASSWORD: pass12
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge

volumes:
  postgres_data:
