services:
  recipe-service:
    # .NET development container
    build:
      context: ./RecipeProcessing.Api/
      dockerfile: ./RecipeProcessing.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    container_name: recipe_service
    ports:
      - "5047:5047"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5047
      - OpenAi:ApiKey=${OpenAi_ApiKey}
      - ConnectionStrings:Database=Host=postgres_db;Database=mealio_db_dev;Username=dev;Password=password
      - ConnectionStrings:Redis=redis:6379
    networks:
      - pg_network
    depends_on:
      - db
      - redis
      - gateway

  gateway:
    container_name: api_gateway
    build:
      context: ./ApiGateway/
      dockerfile: ./ApiGateway/Dockerfile
    volumes:
      - ../ApiGateway/:/app/src
      - /app/obj/ # <- directory won't be mounted
      - /app/bin/
    ports:
      - "5187:5187"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5187
    networks:
      - pg_network

  db:
    # Postgres database
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mealio_db_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg_network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pg_network

networks:
  pg_network:
    name: pg_network
    driver: bridge

volumes:
  postgres_data:
  redis_data:
