services:
  api:
    # .NET development container
    build:
      context: ./
      dockerfile: RecipeProcessing.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug # Use Debug mode for development
    volumes:
      - ../RecipeProcessing.Api/:/src
      - ~/.nuget/packages:/root/.nuget/packages
      - ./Config/OpenAi/Prompts:/Config/OpenAi/Prompts
    ports:
      - "5047:5047"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5047
      - OpenAi:ApiKey=${OpenAi_ApiKey}
    networks:
      - pg_network
    depends_on:
      - db
      - redis
    command: [ "dotnet", "watch", "run", "--project", "../RecipeProcessing.Api/RecipeProcessing.Api.csproj" ]

  db:
    # Postgres database
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mealio_db_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg_network

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pg_network

  db_management:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@localhost.com
      PGADMIN_DEFAULT_PASSWORD: pass12
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
