services:
  nextjs-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    networks:
      - pg_network

networks:
  pg_network:
    name: pg_network
    external: true
